version: '3.8'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-dev-con
    environment:
      MARIADB_ROOT_PASSWORD: 200232
      MARIADB_DATABASE: consultas
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:
