version: '3.8'

services:
  mariadb-dev-con:
    image: mariadb:11
    container_name: mariadb-dev-con
    environment:
      MARIADB_ROOT_PASSWORD: 200232
      MARIADB_DATABASE: consultas
    ports:
      - "3309:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - consultorio_net

  mariadb-dev-con-replica:
    image: mariadb:11
    container_name: mariadb-dev-con-replica
    environment:
      MARIADB_ROOT_PASSWORD: 200232
      MARIADB_DATABASE: consultas
    ports:
      - "3319:3306"
    volumes:
      - mariadb_replica_data:/var/lib/mysql
    networks:
      - consultorio_net

volumes:
  mariadb_data:
  mariadb_replica_data:

networks:
  consultorio_net:
    driver: bridge
