// <auto-generated />
using System;
using Consulltorio_Medico_Consultas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Consulltorio_Medico_Consultas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251029055759_InitialPostgresMigration")]
    partial class InitialPostgresMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Consulltorio_Medico_Consultas.Models.ConsultasMedicasEntity", b =>
                {
                    b.Property<int>("id_consulta_medica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_consulta_medica"));

                    b.Property<string>("diagnostico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fecha")
                        .HasColumnType("date");

                    b.Property<string>("hora")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_centro_medico")
                        .HasColumnType("integer");

                    b.Property<int>("id_empleado")
                        .HasColumnType("integer");

                    b.Property<string>("motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("pacienteid_paciente")
                        .HasColumnType("integer");

                    b.Property<string>("tratamiento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_consulta_medica");

                    b.HasIndex("pacienteid_paciente");

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("Consulltorio_Medico_Consultas.Models.Paciente", b =>
                {
                    b.Property<int>("id_paciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id_paciente"));

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<int>("id_centro_medico")
                        .HasColumnType("integer");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id_paciente");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("Consulltorio_Medico_Consultas.Models.ConsultasMedicasEntity", b =>
                {
                    b.HasOne("Consulltorio_Medico_Consultas.Models.Paciente", "paciente")
                        .WithMany()
                        .HasForeignKey("pacienteid_paciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("paciente");
                });
#pragma warning restore 612, 618
        }
    }
}
