version: '3.8'

services:
  mariadb-dev:
    image: mariadb:11
    container_name: mariadb-dev
    environment:
      MARIADB_ROOT_PASSWORD: 200232
      MARIADB_DATABASE: hospital
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb-init/master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=ROW --bind-address=0.0.0.0

  mariadb-dev-replica:
    image: mariadb:11
    container_name: mariadb-dev-replica
    environment:
      MARIADB_ROOT_PASSWORD: 200232
      MARIADB_DATABASE: hospital
    ports:
      - "3317:3306"
    volumes:
      - mariadb_replica_data:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=ROW --relay-log=mysql-relay-bin --bind-address=0.0.0.0
    depends_on:
      - mariadb-dev

volumes:
  mariadb_data:
  mariadb_replica_data: